import { createFileRoute } from "@tanstack/react-router";
import { CircleDollarSign, PackageCheck, ShoppingBag, TrendingUp, UsersRound } from "lucide-react";

export const Route = createFileRoute("/admin")({ head: () => ({ meta: [
  { title: "Painel da Diretoria — Sistema Themis" }, { name: "description", content: "Visão gerencial do Diretório Acadêmico." }, { property: "og:title", content: "Painel da Diretoria — Sistema Themis" }, { property: "og:description", content: "Pagamentos, inscrições e produção." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: AdminPage });

const payments = [{name:"Marina Oliveira",item:"Camiseta Themis · M",value:"R$ 69,90",date:"Hoje, 18:42"},{name:"Rafael Santos",item:"Semana Jurídica",value:"R$ 35,00",date:"Hoje, 17:20"},{name:"Ana Carolina",item:"Copo Térmico",value:"R$ 49,90",date:"Hoje, 15:08"},{name:"João Pedro",item:"Tirante Institucional",value:"R$ 24,90",date:"Ontem, 21:17"}];
function AdminPage() { return <div className="app-container py-8 sm:py-12"><p className="text-sm font-bold uppercase text-gold">Acesso da diretoria</p><h1 className="mt-1 text-3xl font-bold">Visão geral</h1><p className="mt-2 text-muted-foreground">Lote de setembro · atualização em tempo real simulada</p>
  <div className="mt-7 grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric icon={CircleDollarSign} label="Total arrecadado" value="R$ 8.492" hint="+18% no mês" /><Metric icon={ShoppingBag} label="Pedidos" value="128" hint="42 neste lote" /><Metric icon={UsersRound} label="Inscritos" value="214" hint="76% das vagas" /><Metric icon={TrendingUp} label="Ticket médio" value="R$ 66,34" hint="+R$ 4,20" /></div>
  <div className="mt-7 grid gap-7 lg:grid-cols-[minmax(0,1fr)_340px]"><section className="min-w-0 rounded-xl border border-border bg-card"><div className="flex items-center justify-between border-b border-border p-5"><h2 className="text-lg font-bold">Pagamentos aprovados</h2><span className="rounded-full bg-success-soft px-2 py-1 text-xs font-bold text-success">Automático</span></div><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="bg-muted text-xs uppercase text-muted-foreground"><tr><th className="px-5 py-3">Aluno</th><th className="px-5 py-3">Item</th><th className="px-5 py-3">Valor</th><th className="px-5 py-3">Data</th></tr></thead><tbody>{payments.map((p) => <tr key={p.name} className="border-t border-border"><td className="px-5 py-4 font-bold">{p.name}</td><td className="px-5 py-4 text-muted-foreground">{p.item}</td><td className="px-5 py-4 font-bold">{p.value}</td><td className="px-5 py-4 text-muted-foreground">{p.date}</td></tr>)}</tbody></table></div></section>
    <aside className="rounded-xl border border-border bg-card p-5"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-lg bg-navy-soft text-primary"><PackageCheck size={20} /></span><div><h2 className="font-bold">Resumo de produção</h2><p className="text-xs text-muted-foreground">Pedidos confirmados</p></div></div><div className="mt-6 space-y-5"><Production label="Camisetas" total="45 un." parts="15 P · 20 M · 10 G" pct="88%" /><Production label="Tirantes" total="32 un." parts="Tamanho único" pct="63%" /><Production label="Copos térmicos" total="18 un." parts="500 ml" pct="35%" /></div></aside></div>
  </div>; }
function Metric({ icon: Icon, label, value, hint }: { icon: typeof CircleDollarSign; label:string; value:string; hint:string }) { return <article className="rounded-xl border border-border bg-card p-4 sm:p-5"><Icon size={21} className="text-gold" /><p className="mt-4 text-xs font-bold uppercase text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-extrabold">{value}</p><p className="mt-1 text-xs font-semibold text-success">{hint}</p></article>; }
function Production({ label,total,parts,pct }: {label:string;total:string;parts:string;pct:string}) { return <div><div className="flex justify-between text-sm font-bold"><span>{label}</span><span>{total}</span></div><p className="mt-1 text-xs text-muted-foreground">{parts}</p><div className="mt-2 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-gold" style={{ width: pct }} /></div></div>; }