import { createFileRoute, Link } from "@tanstack/react-router";
import { CheckCircle2, CreditCard, QrCode, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { z } from "zod";
import { Button } from "@/components/ui/button";
import { FakeQrCode } from "@/components/qr-code";
import { money, products } from "@/lib/catalog";

const searchSchema = z.object({ item: z.string().catch("camiseta") });
export const Route = createFileRoute("/checkout")({ validateSearch: (search) => searchSchema.parse(search), head: () => ({ meta: [
  { title: "Finalizar pedido — Sistema Themis" }, { name: "description", content: "Finalize seu pedido ou inscrição." }, { property: "og:title", content: "Finalizar pedido — Sistema Themis" }, { property: "og:description", content: "Pagamento simples e seguro." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: CheckoutPage });

function CheckoutPage() { const { item } = Route.useSearch(); const [method, setMethod] = useState<"pix" | "card">("pix"); const [paid, setPaid] = useState(false); const isEvent = item.startsWith("evento"); const product = products.find((x) => x.id === item) ?? products[0]; const title = isEvent ? "Semana Jurídica 2026" : product.name; const price = isEvent ? (item === "evento-dia" ? 15 : 35) : product.price;
  if (paid) return <div className="app-container grid min-h-[70vh] place-items-center py-12"><div className="max-w-lg text-center"><span className="mx-auto grid size-20 place-items-center rounded-full bg-success-soft text-success"><CheckCircle2 size={42} /></span><h1 className="mt-5 text-3xl font-bold">Pagamento aprovado!</h1><p className="mt-3 text-muted-foreground">Seu {isEvent ? "ingresso" : "pedido"} já está disponível na Área do Aluno.</p><Button asChild size="lg" className="mt-7 w-full"><Link to="/perfil">Acompanhar agora</Link></Button></div></div>;
  return <div className="app-container py-8 sm:py-12"><h1 className="text-3xl font-bold">Finalizar {isEvent ? "inscrição" : "pedido"}</h1><div className="mt-7 grid gap-7 lg:grid-cols-[minmax(0,1fr)_380px]"><div className="space-y-6"><section className="rounded-xl border border-border bg-card p-5"><h2 className="text-lg font-bold">Seus dados</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Nome completo" placeholder="Seu nome" /><Field label="E-mail acadêmico" placeholder="voce@faculdade.edu.br" /><Field label="CPF" placeholder="000.000.000-00" /><Field label="Matrícula" placeholder="202600000" /></div></section>
    <section className="rounded-xl border border-border bg-card p-5"><h2 className="text-lg font-bold">Forma de pagamento</h2><div className="mt-4 grid grid-cols-2 gap-3"><Method active={method === "pix"} onClick={() => setMethod("pix")} icon={QrCode} title="Pix" /><Method active={method === "card"} onClick={() => setMethod("card")} icon={CreditCard} title="Cartão" /></div>{method === "pix" ? <div className="mt-5 flex flex-col items-center rounded-lg bg-muted p-5 text-center"><FakeQrCode /><p className="mt-3 text-sm font-bold">Escaneie para pagar</p><p className="mt-1 text-xs text-muted-foreground">QR Code demonstrativo · válido por 15 minutos</p></div> : <div className="mt-5 grid gap-4"><Field label="Número do cartão" placeholder="0000 0000 0000 0000" /><div className="grid grid-cols-2 gap-4"><Field label="Validade" placeholder="MM/AA" /><Field label="CVV" placeholder="000" /></div></div>}</section></div>
    <aside className="h-fit rounded-xl border border-border bg-card p-5 shadow-sm"><h2 className="text-lg font-bold">Resumo</h2><div className="mt-4 flex justify-between gap-4 border-b border-border pb-4"><span className="font-semibold">{title}</span><span className="font-bold">{money(price)}</span></div><div className="flex justify-between py-4 text-lg font-extrabold"><span>Total</span><span>{money(price)}</span></div><Button size="lg" className="w-full" onClick={() => setPaid(true)}>Confirmar pagamento</Button><p className="mt-3 flex items-center justify-center gap-2 text-xs text-muted-foreground"><ShieldCheck size={15} /> Ambiente de pagamento simulado</p></aside></div></div>;
}
function Field({ label, placeholder }: { label: string; placeholder: string }) { return <label className="grid gap-1.5 text-sm font-bold">{label}<input className="h-12 rounded-lg border border-input bg-background px-3 font-normal outline-none focus:ring-2 focus:ring-ring" placeholder={placeholder} /></label>; }
function Method({ active, onClick, icon: Icon, title }: { active: boolean; onClick: () => void; icon: typeof QrCode; title: string }) { return <button onClick={onClick} className={`flex h-20 flex-col items-center justify-center gap-2 rounded-lg border font-bold ${active ? "border-primary bg-navy-soft text-primary" : "border-border bg-background"}`}><Icon size={23} />{title}</button>; }