import { createFileRoute, Link } from "@tanstack/react-router";
import { CalendarDays, Clock3, MapPin, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import hero from "@/assets/semana-juridica.jpg";

export const Route = createFileRoute("/eventos")({ head: () => ({ meta: [
  { title: "Semana Jurídica 2026 — Sistema Themis" }, { name: "description", content: "Inscreva-se na Semana Jurídica 2026." }, { property: "og:title", content: "Semana Jurídica 2026" }, { property: "og:description", content: "Três dias de debates, carreira e conexões." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: EventPage });

function EventPage() { const [ticket, setTicket] = useState("completo"); return <div className="app-container py-5 sm:py-10"><img src={hero} alt="Semana Jurídica 2026" width={1600} height={912} className="aspect-[16/9] w-full rounded-xl object-cover grayscale" />
  <div className="mt-7 grid gap-8 lg:grid-cols-[minmax(0,1fr)_380px]"><div><span className="text-sm font-bold uppercase text-gold">Evento presencial</span><h1 className="mt-2 text-3xl font-bold sm:text-4xl">Semana Jurídica 2026</h1><div className="mt-5 grid gap-3 text-sm sm:grid-cols-3"><Info icon={CalendarDays} text="22–24 de setembro" /><Info icon={Clock3} text="18h às 22h" /><Info icon={MapPin} text="Auditório Central" /></div><hr className="my-7 border-border" /><h2 className="text-xl font-bold">Sobre o evento</h2><p className="mt-3 leading-7 text-muted-foreground">Uma jornada acadêmica com palestras, mesas de debate e oportunidades de networking. Nesta edição, especialistas discutem os caminhos do Direito contemporâneo e as novas possibilidades de carreira.</p><h2 className="mt-7 text-xl font-bold">Programação</h2><div className="mt-3 space-y-3">{["22 set · Direito, tecnologia e sociedade", "23 set · Carreiras jurídicas na prática", "24 set · Tribunal simulado e encerramento"].map((x) => <div key={x} className="rounded-lg border border-border bg-card p-4 font-semibold">{x}</div>)}</div></div>
    <aside className="h-fit rounded-xl border border-border bg-card p-5 shadow-sm lg:sticky lg:top-24"><h2 className="text-lg font-bold">Escolha seu ingresso</h2><div className="mt-4 space-y-3">{[{ id:"completo", title:"Passaporte completo", price:"R$ 35,00" }, { id:"dia", title:"Ingresso diário", price:"R$ 15,00" }].map((item) => <button key={item.id} onClick={() => setTicket(item.id)} className={`grid w-full grid-cols-[1fr_auto] items-center rounded-lg border p-4 text-left ${ticket === item.id ? "border-primary bg-navy-soft" : "border-border"}`}><span className="font-bold">{item.title}</span><span className="font-extrabold">{item.price}</span></button>)}</div><Button asChild size="lg" className="mt-5 w-full"><Link to="/checkout" search={{ item: `evento-${ticket}` }}>Realizar Inscrição</Link></Button><p className="mt-3 flex items-center justify-center gap-2 text-xs text-muted-foreground"><ShieldCheck size={15} /> Inscrição segura e confirmação imediata</p></aside>
  </div></div>; }
function Info({ icon: Icon, text }: { icon: typeof CalendarDays; text: string }) { return <span className="flex items-center gap-2 font-semibold"><Icon size={19} className="text-gold" />{text}</span>; }